/**
 * License Validator Service
 * Validates license codes against PC identifier
 * Prevents unauthorized distribution and installation
 * 
 * IMPORTANT: License codes MUST be generated by the app maker only
 * via a secure backend endpoint. Users can only VALIDATE codes.
 */

import { getPCIdentifier } from './pcIdentifier';

const LICENSE_KEY = '_license_code';
const LICENSE_PC_ID_KEY = '_license_pc_id';
const LICENSE_EXPIRY_KEY = '_license_expiry';

/**
 * INTERNAL ONLY - Generate license code
 * This should ONLY be called by the app maker/developer
 * in a secure backend environment, NOT in the client
 * 
 * In production:
 * - Create a backend endpoint (e.g., /api/admin/generate-license)
 * - Require admin authentication
 * - Only the app maker can access this
 * - Provide generated codes to customers
 */
const _generateLicenseCodeInternal = (pcId, expiryDays = 365) => {
  const expiryDate = new Date();
  expiryDate.setDate(expiryDate.getDate() + expiryDays);
  
  const expiryTimestamp = expiryDate.getTime();
  const checksum = createChecksum(pcId, expiryTimestamp);
  
  // Format: PC_ID|EXPIRY|CHECKSUM
  const license = `${pcId}|${expiryTimestamp}|${checksum}`;
  return encodeToReadableFormat(license);
};

/**
 * Validate a license code
 * Users paste codes here - codes must be generated by app maker
 * Returns { valid: boolean, error: string|null, details: object }
 */
export const validateLicense = (licenseCode, currentPCId = null) => {
  try {
    const pcId = currentPCId || getPCIdentifier();

    // Check if license is stored
    const storedLicense = localStorage.getItem(LICENSE_KEY);
    if (!storedLicense && !licenseCode) {
      return {
        valid: false,
        error: 'No license found. Please enter a license code.',
        details: null
      };
    }

    const licenseToValidate = licenseCode || storedLicense;

    // Decode license
    const decodedLicense = decodeFromReadableFormat(licenseToValidate);
    
    if (!decodedLicense) {
      return {
        valid: false,
        error: 'License code format is invalid. Please check and try again.',
        details: null
      };
    }
    
    const parts = decodedLicense.split('|');

    if (parts.length !== 3) {
      return {
        valid: false,
        error: 'Invalid license format.',
        details: null
      };
    }

    const [licensePCId, expiryTimestampStr, checksum] = parts;

    // Verify checksum (must use the string form from license, not parsed number)
    const expectedChecksum = createChecksum(licensePCId, expiryTimestampStr);
    if (checksum !== expectedChecksum) {
      return {
        valid: false,
        error: 'License code is corrupted or invalid.',
        details: null
      };
    }

    // Check PC ID match
    if (licensePCId !== pcId) {
      return {
        valid: false,
        error: `License is tied to different PC. This PC: ${pcId.substring(0, 8)}... Licensed PC: ${licensePCId.substring(0, 8)}...`,
        details: { currentPC: pcId, licensedPC: licensePCId }
      };
    }

    // Check expiry
    const expiryTimestamp = parseInt(expiryTimestampStr);
    const expiry = new Date(expiryTimestamp);
    const now = new Date();

    if (now > expiry) {
      return {
        valid: false,
        error: `License expired on ${expiry.toLocaleDateString()}. Please renew.`,
        details: { expiry: expiry.toISOString() }
      };
    }

    // All checks passed
    const daysUntilExpiry = Math.ceil((expiry - now) / (1000 * 60 * 60 * 24));

    return {
      valid: true,
      error: null,
      details: {
        pcId: licensePCId,
        expiry: expiry.toISOString(),
        daysUntilExpiry,
        message: `License valid. Expires in ${daysUntilExpiry} days.`
      }
    };
  } catch (error) {
    console.error('Error validating license:', error);
    return {
      valid: false,
      error: 'Error validating license. Please try again.',
      details: null
    };
  }
};

/**
 * Save license to localStorage
 */
export const saveLicense = (licenseCode) => {
  const validation = validateLicense(licenseCode);

  if (!validation.valid) {
    return validation;
  }

  try {
    localStorage.setItem(LICENSE_KEY, licenseCode);
    localStorage.setItem(LICENSE_PC_ID_KEY, getPCIdentifier());
    localStorage.setItem(LICENSE_EXPIRY_KEY, validation.details.expiry);

    return {
      valid: true,
      error: null,
      details: {
        ...validation.details,
        message: 'License saved successfully!'
      }
    };
  } catch (error) {
    return {
      valid: false,
      error: 'Could not save license to storage.',
      details: null
    };
  }
};

/**
 * Check if app is licensed (startup check)
 */
export const isLicensed = () => {
  const storedLicense = localStorage.getItem(LICENSE_KEY);

  if (!storedLicense) {
    return false;
  }

  const validation = validateLicense(storedLicense);
  return validation.valid;
};

/**
 * Get license info
 */
export const getLicenseInfo = () => {
  const storedLicense = localStorage.getItem(LICENSE_KEY);

  if (!storedLicense) {
    return {
      licensed: false,
      info: null
    };
  }

  const validation = validateLicense(storedLicense);

  return {
    licensed: validation.valid,
    info: validation.details || {
      error: validation.error
    }
  };
};

/**
 * Create checksum for license validation
 * Simple checksum to verify license integrity
 */
const createChecksum = (pcId, expiryTimestamp) => {
  const combined = `${pcId}|${expiryTimestamp}`;
  let checksum = 0;

  for (let i = 0; i < combined.length; i++) {
    checksum += combined.charCodeAt(i);
  }

  return (checksum % 10000).toString(16).padStart(4, '0');
};

/**
 * Encode license to readable format (base64)
 */
const encodeToReadableFormat = (license) => {
  try {
    // Use browser's btoa (base64 encode)
    return btoa(unescape(encodeURIComponent(license)));
  } catch (e) {
    console.error('Encoding error:', e);
    return null;
  }
};

/**
 * Decode license from readable format
 */
const decodeFromReadableFormat = (license) => {
  try {
    // Use browser's atob (base64 decode)
    return decodeURIComponent(escape(atob(license)));
  } catch (e) {
    console.error('Decoding error:', e);
    return null;
  }
};

/**
 * Remove/Clear license
 */
export const clearLicense = () => {
  localStorage.removeItem(LICENSE_KEY);
  localStorage.removeItem(LICENSE_PC_ID_KEY);
  localStorage.removeItem(LICENSE_EXPIRY_KEY);
};

/**
 * Export module
 */
export default {
  validateLicense,
  saveLicense,
  isLicensed,
  getLicenseInfo,
  clearLicense
};
